### ISSUE TITLE
MakeAuth request is PHONE_NUMBER_UNOCCUPIED error

### ISSUE THREAD

**Issue by majid23** [sochix/TLSharp#104]
Hello,
In Authorize i request code and i give it in my phone from Telegram.
hash = await client.SendCodeRequest(NumberToAuthenticate);
but when i send code for Authorize with MakeAuth function i have PHONE_NUMBER_UNOCCUPIED error and occur Exception.
my code is:

        TelegramClient client;
        string NumberToAuthenticate;
        string hash;

        public MainWindow()
        {
            InitializeComponent();
            var store = new FileSessionStore();
            client = new TelegramClient(store, "session");
        }

        private async void button_start_Click(object sender, RoutedEventArgs e)
        {

            await client.Connect();
            
            if (!client.IsUserAuthorized())
            {
                NumberToAuthenticate = textBox_PhonNumber.Text;
                hash = await client.SendCodeRequest(NumberToAuthenticate);
                
                textBlock_Result.Text = "Enter Code that sent to your phone.";
            }
            else
            {
                textBlock_Result.Text = "User has a session.";
            }
        }

        private async void button_SendCode_Click(object sender, RoutedEventArgs e)
        {
            var user = await client.MakeAuth(NumberToAuthenticate, hash, textBox_Code.Text);
            if(user==null)
            {
                MessageBox.Show("Error in Authenticate.", "Error", MessageBoxButton.OK);
            }
        }

stack trace is:
   at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, MTProtoRequest request) in F:\Dev\Tel\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 288
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, MTProtoRequest request) in F:\Dev\Tel\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 193
   at TLSharp.Core.Network.MtProtoSender.<Recieve>d__9.MoveNext() in F:\Dev\Tel\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<MakeAuth>d__13.MoveNext() in F:\Dev\Tel\TLSharp-master\TLSharp.Core\TelegramClient.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TelExplorer.MainWindow.<button_SendCode_Click>d__5.MoveNext() in F:\Dev\Tel\TLSharp-master-my\TelExplorer\MainWindow.xaml.cs:line 54
Please Help me Why this error occur.

**Comment by Shablah** [comment]
I have the same problem :-(

This is the code :




any news?

**Comment by Shablah** [comment]
Public Async Function AuthUser() As Task
        Try
            Dim store = New FileSessionStore()
            Dim client = New TelegramClient(store, "session")

            Await client.Connect()

            'Dim Code  = Await client.SendCodeRequest("XXXXXXXXXXX")

            Dim Res = Await client.IsPhoneRegistered("XXXXXXXXXXXX")

            Dim user = Await client.MakeAuth("XXXXXXXXXXXX", "YYYYYYYYYYYYYY", "ZZZZZ")
              
        Catch Err As Exception
            MsgBox(Err.ToString())
        End Try

**Comment by andik1212** [comment]
I have same problem/
code:
`         static async void TelegConn()
        {
            var store = new FileSessionStore();
            var client = new TelegramClient(store, "session123");
            await client.Connect();
            var result = await client.IsPhoneRegistered(NumberToAuthenticate);
            if (!result)
            {
                var hash = await client.SendCodeRequest(NumberToAuthenticate);
                var code = Console.ReadLine();
                var user = await client.MakeAuth(NumberToAuthenticate, hash, code);
            }
//....
        }`

**Comment by andik1212** [comment]
I tried to use a version up to "Merge pull request #93 from dmitriyett/master" commit and it is workin.
hope, that this helps somebody.

**Comment by headria** [comment]
hi every body i get a lot of problem but when i remove "await" no problem showed for me and Api it's work ok .

**Comment by mikachi** [comment]
I have the same issue guys.
@Shablah, do you get code via SMS?
I have a feeling that TL team has changed something...
I am on chat with them now, maybe they can pour some light on the issue
