### ISSUE TITLE
Get "STORE_INVALID_OBJECT_TYPE" error and NULL hash when SendCodeRequest

### ISSUE THREAD

**Issue by Ramin-Bateni** [sochix/TLSharp#128]
VS: **2015**
App.config is set
_Ip address in Session.cs :_
`defaultConnectionAddress `= "149.154.175.50"
`defaultConnectionPort `= 443
___________________________________________
Now, when i call `SendCodeRequest `and debug line by line >>
**First >**
It use "149.154.175.50:443" and return error `PHONE_MIGRATE_4` from `HandleRpcResult `method.
**Then >**
The the library handle it and use `ReconnectToDc(4)` and continue with "91.108.4.182:443"
**Finally >**
It return `STORE_INVALID_OBJECT_TYPE` from `HandleRpcResult `method.
**Result is >**
hash == null
___________________________________________
Note: I removed `session.dat` and tried again but no help. 
Note: Also I test it by `91.108.56.165:443` IP without any changes in result.
What is my mistake? Or How i can solve it?

Stack Trace:
Test Name:	AuthUser
Test FullName:	TLSharp.Tests.TLSharpTests.AuthUser
Test Source:	D:\Documents\Visual Studio 2015\Projects\TLSharp-master\TLSharp.Tests\TLSharpTests.cs : line 42
Test Outcome:	Failed
Test Duration:	0:00:03/2200664

Result StackTrace:	
```
at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, MTProtoRequest request) in D:\Documents\Visual Studio 2015\Projects\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 288
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, MTProtoRequest request) in D:\Documents\Visual Studio 2015\Projects\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 193
   at TLSharp.Core.Network.MtProtoSender.<Recieve>d__9.MoveNext() in D:\Documents\Visual Studio 2015\Projects\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<SendCodeRequest>d__12.MoveNext() in D:\Documents\Visual Studio 2015\Projects\TLSharp-master\TLSharp.Core\TelegramClient.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at TLSharp.Core.TelegramClient.<SendCodeRequest>d__12.MoveNext() in D:\Documents\Visual Studio 2015\Projects\TLSharp-master\TLSharp.Core\TelegramClient.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Tests.TLSharpTests.<AuthUser>d__13.MoveNext() in D:\Documents\Visual Studio 2015\Projects\TLSharp-master\TLSharp.Tests\TLSharpTests.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Result Message:	
Test method TLSharp.Tests.TLSharpTests.AuthUser threw exception: 
System.InvalidOperationException: STORE_INVALID_OBJECT_TYPE


```

**Comment by eaba** [comment]
Hello, I experienced this issue STORE_INVALID_OBJECT_TYPE
To resolve, try other IPs, the current IP might be unavailable!
Thats how I resolved my issue!

**Comment by knocte** [comment]
@eaba can you elaborate?

I'm having the same problem.

**Comment by eaba** [comment]
Hello @knocte in the Session.cs change the ip here `private const string defaultConnectionAddress = "91.108.56.165";`

**Comment by LukZucca** [comment]
Hi all, I have had the same problem of Ramin-Batemi. I followed the eaba's suggestion, but without succesfull because my Session.cs has by default the code `private const string defaultConnectionAddress = "91.108.56.165";`
Did anyone find a solution for "STORE_INVALID_OBJECT_TYPE " or suggestions? Thank you in advance.
I am using vs2015 c#

**Comment by brahmanzadeh** [comment]
Hello all, i had same problem with Ramin, I just changed IP Address in Session.cs into following:
        private const string defaultConnectionAddress = "149.154.175.100";
        private const int defaultConnectionPort = 443;
Rebuild the project and re-reference the dll in my Solution and it works like a charm.
btw, i am using VS2015, VB .NET and Windows 7 Ultimate x64.
