### ISSUE TITLE
NETWORK_MIGRATE_4

### ISSUE THREAD

**Issue by oram83** [sochix/TLSharp#144]
Can't seems to connect.
I tried to run the test and also via WinForms but I get this same response.

Already tried to clean solution and delete session.dat, but it didn't help.

Full stacktrace

Test Name:	AuthUser
Test FullName:	TLSharp.Tests.TLSharpTests.AuthUser
Test Source:	D:\Sources\TLSharp-master\TLSharp.Tests\TLSharpTests.cs : line 46
Test Outcome:	Failed
Test Duration:	0:00:03.807886

Result StackTrace:	
at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, MTProtoRequest request) in D:\Sources\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 288
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, MTProtoRequest request) in D:\Sources\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 193
   at TLSharp.Core.Network.MtProtoSender.<Recieve>d__9.MoveNext() in D:\Sources\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<SendCodeRequest>d__12.MoveNext() in D:\Sources\TLSharp-master\TLSharp.Core\TelegramClient.cs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at TLSharp.Core.TelegramClient.<SendCodeRequest>d__12.MoveNext() in D:\Sources\TLSharp-master\TLSharp.Core\TelegramClient.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Tests.TLSharpTests.<AuthUser>d__15.MoveNext() in D:\Sources\TLSharp-master\TLSharp.Tests\TLSharpTests.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Result Message:	
Test method TLSharp.Tests.TLSharpTests.AuthUser threw exception: 
System.InvalidOperationException: NETWORK_MIGRATE_4

**Comment by RaaaGEE** [comment]
Try it: https://github.com/sochix/TLSharp/pull/135/commits/7ceab708d1b2ed40ba7fca971a5122d97bb266ef
