### ISSUE TITLE
SendMessage Failed. (Assert.IsTrue failed)

### ISSUE THREAD

**Issue by DavLutsan** [sochix/TLSharp#15]
i passed TestConnection and AuthUser successfully, 
but in SendMessage Test i got this error:

Test Name:	SendMessage
Test FullName:	TLSharp.Tests.NotificatioClientTests.SendMessage
Test Source:	F:\Telegram\003 - TLSharp-master\TLSharp-master\TLSharp.Tests\NotificatioClientTests.cs : line 101
Test Outcome:	Failed
Test Duration:	0:00:02.85505

Result StackTrace:	
at TLSharp.Tests.NotificatioClientTests.<SendMessage>d__16.MoveNext() in F:\Telegram\003 - TLSharp-master\TLSharp-master\TLSharp.Tests\NotificatioClientTests.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Result Message:	Assert.IsTrue failed.

any idea?

**Comment by sochix** [comment]
Did you entered a correct Telegram code in Auth method?

**Comment by DavLutsan** [comment]
yeah. and i passed AuthTest

**Comment by sochix** [comment]
Delete session.dat and try again.

**Comment by hamidpp** [comment]
hi: i invoke AuthUser method success and create session.dat but  i get this error after invoke sendMessage method in test mode :
unable to cast object of type 'TLSharp.Core.MTProto.UserContactCostructor' to type TLSharp.Core.MTProto.UserSelfCostructor
please help me.
