### ISSUE TITLE
PhoneMigrationException and PHONE_CODE_EXPIRED on a fresh project

### ISSUE THREAD

**Issue by Pro-Ton** [sochix/TLSharp#305]
The PhoneMigrationException occur on this line :
`            bool isReged = await client.IsPhoneRegisteredAsync(unumber);
`

No problem when sending code...
`            var hash = await client.SendCodeRequestAsync(unumber);
`

And PHONE_CODE_EXPIRED on this:
`   TLUser user = await client.MakeAuthAsync(unumber, hash, code);
`

TLSharp.Core.Network.PhoneMigrationException was unhandled by user code
  HResult=-2146233088
  Message=Phone number registered to a different DC: 4. See: https://github.com/sochix/TLSharp#i-get-a-xxxmigrationexception-or-a-migrate_x-error
  Source=TLSharp.Core
  StackTrace:
       at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
       at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
       at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at TLSharp.Core.TelegramClient.<IsPhoneRegisteredAsync>d__11.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at tgcrawl.Form1.<button1_Click>d__4.MoveNext() in c:\users\edge\documents\visual studio 2015\Projects\tgcrawl\tgcrawl\Form1.cs:line 62
  InnerException:

**Comment by Pro-Ton** [comment]
It seems that the `MakeAuthAsync` method should called in the same client and connection that the `SendCodeRequestAsync` method was called.
