### ISSUE TITLE
"Can't decode packet"

### ISSUE THREAD

**Issue by sresoft** [sochix/TLSharp#353]
when I want to download multiple photos, after a while i get this error:
"Can't decode packet"

here is my code:
am I doing something wrong?
```
var inputPeer = new TLInputPeerUser() { user_id = user.id };
            var res = await client.SendRequestAsync<TLMessagesSlice>(new TLRequestGetHistory() { peer = inputPeer,limit=200 });
            var photos = res.messages.lists
                .OfType<TLMessage>()
                .Where(m => m.media != null)
                .Select(m => m.media)
                .OfType<TLMessageMediaPhoto>()
                .Select(md => md.photo)
                .OfType<TLPhoto>();
                

            foreach (TLPhoto ph in photos)
            {
                var photoSize = ph.sizes.lists.OfType<TLPhotoSize>().Last();
                TLFileLocation tf = (TLFileLocation)photoSize.location;

                var resFile = await client.GetFile(new TLInputFileLocation
                {

                    local_id = tf.local_id,
                    secret = tf.secret,
                    volume_id = tf.volume_id
                }
                    ,
                    0);

                FileStream fs = new FileStream("e:\\bk\\"+DateTime.Now.Ticks+".jpg", FileMode.OpenOrCreate);
                StreamWriter sw = new StreamWriter(fs);
                fs.Write(resFile.bytes, 0, resFile.bytes.Length);
                fs.Flush();
                fs.Close();
            }
```

**Comment by knocte** [comment]
> "Can't decode packet"

Please post the full stacktrace.

**Comment by sresoft** [comment]
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=Can't decode packet
  Source=TLSharp.Core
  StackTrace:
       at TLSharp.Core.Network.MtProtoSender.DecodeMessage(Byte[] body) in E:\Downloads\TLSharp-master(1)\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 113
       at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext() in E:\Downloads\TLSharp-master(1)\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 139
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at TLSharp.Core.TelegramClient.<ConnectAsync>d__8.MoveNext() in E:\Downloads\TLSharp-master(1)\TLSharp-master\TLSharp.Core\TelegramClient.cs:line 76
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at TLSharp.Core.TelegramClient.<GetFile>d__24.MoveNext() in E:\Downloads\TLSharp-master(1)\TLSharp-master\TLSharp.Core\TelegramClient.cs:line 328
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at TLSharp.Client.Form1.<button3_Click>d__14.MoveNext() in E:\Downloads\TLSharp-master(1)\TLSharp-master\TLSharp.Client\Form1.cs:line 293
  InnerException:

**Comment by knocte** [comment]
Thanks

**Comment by sresoft** [comment]
Thank yourself. :+1:

**Comment by Dian8** [comment]
Hello! Have somebody explored this issue?
