### ISSUE TITLE
Couldnt Connect To Server Error after 4 times calling method

### ISSUE THREAD

**Issue by npsniloo** [sochix/TLSharp#358]
hi,
I have a schedule which get the list of client dialogs,it gets an error after a while with this stack trace:

> 
at TLSharp.Core.Network.TcpTransport.<Send>d__3.MoveNext() in D:\Projects\Telegram\sochix-TLSharp-6b3c96e\TLSharp.Core\Network\TcpTransport.cs:line 27
--- End of stack trace from previous location where exception was thrown ---

here is my code:
 var t =await client.GetUserDialogsAsync();
            var ss = (TLAbsDialogs)t;

and eventually this error:
 System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine

**Comment by knocte** [comment]
That is not the whole stacktrace, it only has 1 line of the stack. Please paste the whole stacktrace.

**Comment by npsniloo** [comment]
{"Client not connected to server."}   


at TLSharp.Core.Network.TcpTransport.<Send>d__3.MoveNext() in D:\Projects\Telegram\sochix-TLSharp-6b3c96e\TLSharp.Core\Network\TcpTransport.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TLSharp.Core.Network.MtProtoSender.<Send>d__7.MoveNext() in D:\Projects\Telegram\sochix-TLSharp-6b3c96e\TLSharp.Core\Network\MtProtoSender.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TLSharp.Core.Network.MtProtoSender.<Send>d__6.MoveNext() in D:\Projects\Telegram\sochix-TLSharp-6b3c96e\TLSharp.Core\Network\MtProtoSender.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TLSharp.Core.TelegramClient.<SendRequestAsync>d__17`1.MoveNext() in D:\Projects\Telegram\sochix-TLSharp-6b3c96e\TLSharp.Core\TelegramClient.cs:line 204
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<GetUserDialogsAsync>d__21.MoveNext() in D:\Projects\Telegram\sochix-TLSharp-6b3c96e\TLSharp.Core\TelegramClient.cs:line 249
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TeleBoosterLandLib.TelegramClientClass.<GetLastMessagesSeen>d__10.MoveNext() in D:\TeleBoosterland\TeleBoosterLandLib\TelegramClientClass.cs:line 81

**Comment by hosseinGanjyar** [comment]
Are u solved problem?

**Comment by knocte** [comment]
Please update to latest git master and try again. If you reproduce this problem again, reopen this issue with a full ex.ToString() pasted here.
