### ISSUE TITLE
AUTH_KEY_UNREGISTERED

### ISSUE THREAD

**Issue by omarmaher100** [sochix/TLSharp#378]
when i run the code from console app its run good
but when i'm tring to run it from windows service i got this Exception 
Exception Message : AUTH_KEY_UNREGISTERED

Exception Description :    at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request) in E:\TLSharp-master\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 318
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request) in E:\TLSharp-master\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 206
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext() in E:\TLSharp-master\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<SendRequestAsync>d__17`1.MoveNext() in E:\TLSharp-master\TLSharp-master\TLSharp.Core\TelegramClient.cs:line 214
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<GetUserDialogsAsync>d__21.MoveNext() in E:\TLSharp-master\TLSharp-master\TLSharp.Core\TelegramClient.cs:line 258
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Arcom.WinService.SocialMedia.SocialMedia.<SendMSGtoChannel>d__28.MoveNext() in E:\Arcom.WinService.SocialMedia\SocialMedia.cs:line 307
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Arcom.WinService.SocialMedia.SocialMedia.<HandleBussinse>d__23.MoveNext() in E:\Arcom.WinService.SocialMedia\SocialMedia.cs:line 153
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Arcom.WinService.SocialMedia.SocialMedia.<DoWork>d__22.MoveNext() in E:\Arcom.WinService.SocialMedia\SocialMedia.cs:line 129

Exception Source : TLSharp.Core

Exception InnerException : 

Exception Data : System.Collections.ListDictionaryInternal

Exception HelpLink : 

Exception Method : Boolean HandleRpcResult(UInt64, Int32, System.IO.BinaryReader, TeleSharp.TL.TLMethod)

**Comment by omarmaher100** [comment]
I solved it 
you should call 
         var client = new TelegramClient(apiId, apiHash);
            await client.ConnectAsync();
            var hash = await client.SendCodeRequestAsync("Phone Number");
on every machine which your code will run on it
