### ISSUE TITLE
mvc 5 Arithmetic operation resulted in an overflow. on async method

### ISSUE THREAD

**Issue by blacklabelmee** [sochix/TLSharp#388]
I am using TLSharp package in mvc 5 for sending notification to the users via telegram api .

with this method i add users to my contacts.

`public async Task<bool> addNumberToContacts(string phone,string firstName,string lastName)
    {

            var contacts = new TLVector<TLInputPhoneContact>();
            contacts.lists.Add(new TLInputPhoneContact { first_name = firstName, last_name = lastName, phone = phone });

            //Create request 
            var req = new TLRequestImportContacts()
            {
                contacts = contacts
            };

            var ReqResult =  await client.SendRequestAsync<TLImportedContacts>(req);

            if (ReqResult.imported.lists.Count >= 1)
            {
                return true;
            }
            return false;

    }`

i get error

> "Arithmetic operation resulted in an overflow."

in this line :

`                await client.SendRequestAsync<TLImportedContacts>(req);
`

**Comment by knocte** [comment]
Please post the full stack trace.

**Comment by blacklabelmee** [comment]
`>    at TLSharp.Core.Network.TcpTransport.<Receieve>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<SendRequestAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TheStickProject.Utilities.telegramManger.<addNumberToContacts>d__2.MoveNext() in c:\testproj\testproj\Utilities\telegramManger.cs:line 98`

**Comment by blacklabelmee** [comment]
it works in console application but no  chance in asp.net

**Comment by blacklabelmee** [comment]
@knocte  hello again did you try that ? was there a problem or it's my codes that are wrong?

**Comment by knocte** [comment]
You didn't post the whole exception (exception name + exception message + exception stacktrace).

**Comment by blacklabelmee** [comment]
> system.overflowException 



> "Arithmetic operation resulted in an overflow."



> Data : {System.Collections.ListDictionaryInternal}



> HResult : -2146233066



> inner Exception : null



> source : TLSharp.Core



> StackTrace : 
>    at TLSharp.Core.Network.TcpTransport.<Receieve>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at TLSharp.Core.TelegramClient.<SendRequestAsync>d__18`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at BLL.telegramManger.<addNumberToContacts>d__2.MoveNext() in c:\ThetelegramProject\BLL\telegramManger.cs:line 83



> Target Site: {Void MoveNext()}

**Comment by blacklabelmee** [comment]
thank you for your response . is that all that is needed ?

**Comment by blacklabelmee** [comment]
@knocte  thank you for your response . is that all that is needed ?

**Comment by Ozymandy** [comment]
Have the same problem with OverFlowException

**Comment by blacklabelmee** [comment]
@Ozymandy are you using asp.net 4.5 or asp.net core ?

**Comment by Ozymandy** [comment]
@blacklabelmee no, just desktop app

**Comment by kekinator1337** [comment]
//Hope this code helps you guys, who encountered same problem as i.
FileSessionStore store = new FileSessionStore();
TelegramClient tgClient;

public MainWindow()
        {
            tgClient = new TelegramClient(your_app_id, your_app_hash, store, "session");
            _tgClient.ConnectAsync();_ //this is incorrect, because you have to use this call within async method and MainWindow() constructor is not an async method.
            AsyncMethod(); //You have to use something like this: create separate async method and connect to your client within that method
        }

        public async void AsyncMethod()
        {
            await tgClient.ConnectAsync();
            bool isRegistred = await tgClient.IsPhoneRegisteredAsync("3806222214555"); //when ConnectAsync() called incorrect this line would give an Overflow Error.
        }

**Comment by Hamidnwo** [comment]
Hi, I found the source of this error:
The problem is that we are sending the same request in a short period of time.
The worked around is that we should avoid re-sending similar requests consecutively by sending a dummy requests in between.
