### ISSUE TITLE
problem authenticating code from a server app

### ISSUE THREAD

**Issue by npsniloo** [sochix/TLSharp#392]
this is my error when I call this method:
 await client.MakeAuthAsync("+mynumber", hash code, code);

TLSharp.Core.Network.PhoneMigrationException: Phone number registered to a different DC: 4. See: https://github.com/sochix/TLSharp#i-get-a-xxxmigrationexception-or-a-migrate_x-error
   at TeleBoosterLandLib.TelegramClientClass.<ConnectClient>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TeleBoosterLandLib.TelegramClientClass.<GetLastMessagesSeen>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TeleBoosterLandLib.RunBot.<UpdateMessagesView>d__17.MoveNext()

**Comment by ayazzali** [comment]
https://github.com/sochix/TLSharp/issues/395 
try without '+'
