### ISSUE TITLE
How to bind UserProfilePhoto of TLuser to WPF Image in TLSharp

### ISSUE THREAD

**Issue by VahedCivil** [sochix/TLSharp#430]
Hi all
This my code to bind the UserProfilePhoto of TLuser.

```
private async void GetContactsButton_Click(object sender, RoutedEventArgs e)
{
    TeleSharp.TL.Contacts.TLContacts result;
    //get available contacts
    try
    {
        result = await client.GetContactsAsync();
    }
    catch (Exception ex)
    {
        MessageBox.Show(ex.Message + "\n" + ex.InnerException);
        return;
    }
    var contacts = result.users.lists.Where(x => x.GetType() == typeof(TLUser)).Cast<TLUser>();
    ContactsDataGrid.ItemsSource = contacts;
    //foreach (var contact in contacts)
    //{
    //}
}

private void ContactsDataGrid_SelectionChanged(object sender, System.Windows.Controls.SelectionChangedEventArgs e)
{
        TLUser selectedUser = (TLUser) ContactsDataGrid.SelectedItem;
        if (selectedUser != null)
        {
            var bytes = selectedUser.photo.Serialize();

            UserImage.Source = ByteToImage(bytes);
        }
}

public BitmapImage ByteToImage(byte[] bytes)
{
        using (var ms = new MemoryStream(bytes))
        {
            var image = new BitmapImage();
            image.BeginInit();
            image.CacheOption = BitmapCacheOption.OnLoad;
            image.StreamSource = ms;
            image.EndInit();
            return image;
        }
}
```

But it's not work. How I can get photo profile of contacts list and set to UserImage.Source ?

**Comment by knocte** [comment]
The sentence `but it's not work` doesn't provide enough information of how it doesn't work. Please provide more details. Error? Exception?

**Comment by VahedCivil** [comment]
Hi knocte 
Thank you for your reply.
The Exception is:
![image](https://cloud.githubusercontent.com/assets/26754783/24449935/330bec3a-148e-11e7-93bf-69234ce1c381.png)

**Comment by knocte** [comment]
Thanks for the screenshot but it's better to report the exceptions in text format, please copy paste the whole exception+stacktrace in the original description of the github issue.

**Comment by knocte** [comment]
(Oops, closed by mistake.)

**Comment by VahedCivil** [comment]
The Exception is:
An unhandled exception of type 'System.NotSupportedException' occurred in PresentationCore.dll
Additional information: No imaging component suitable to complete this operation was found.

Inner Exception is:
{"The component cannot be found. (Exception from HRESULT: 0x88982F50)"}

Stacktrace:
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at Vahed_Telegram_Demo.MainWindow.ByteToImage(Byte[] bytes) in E:\ProjectTraining\C#\Telegram API\Vahed Telegram Demo\Vahed Telegram Demo\MainWindow.xaml.cs:line 184
   at Vahed_Telegram_Demo.MainWindow.ContactsDataGrid_SelectionChanged(Object sender, SelectionChangedEventArgs e) in E:\ProjectTraining\C#\Telegram API\Vahed Telegram Demo\Vahed Telegram Demo\MainWindow.xaml.cs:line 172
   at System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.DataGrid.OnSelectionChanged(SelectionChangedEventArgs e)
   at System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.SelectedItemCollection.EndUpdateSelectedItems()
   at System.Windows.Controls.Primitives.MultiSelector.EndUpdateSelectedItems()
   at System.Windows.Controls.DataGrid.MakeFullRowSelection(ItemInfo info, Boolean allowsExtendSelect, Boolean allowsMinimalSelect)
   at System.Windows.Controls.DataGrid.HandleSelectionForCellInput(DataGridCell cell, Boolean startDragging, Boolean allowsExtendSelect, Boolean allowsMinimalSelect)
   at System.Windows.Controls.DataGridCell.OnAnyMouseLeftButtonDown(MouseButtonEventArgs e)
   at System.Windows.Controls.DataGridCell.OnAnyMouseLeftButtonDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Vahed_Telegram_Demo.App.Main()
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by hadi77ir** [comment]
You can try `System.Windows.Media.Imaging.BitmapFrame.Create(drawingStream);` instead of conversion to `BitmapImage`.

**Comment by VahedCivil** [comment]
Thank you for.
I used follow code and I get same exception
```
        private void ContactsDataGrid_SelectionChanged(object sender,
            System.Windows.Controls.SelectionChangedEventArgs e)
        {
            TLUser selectedUser = (TLUser) ContactsDataGrid.SelectedItem;
            if (selectedUser != null)
            {
                var buffer = selectedUser.photo.Serialize();
                MemoryStream drawingStream = new MemoryStream(buffer);
                //MemoryStream drawingStream = new MemoryStream(buffer, 0, buffer.Length);
                BitmapFrame b = System.Windows.Media.Imaging.BitmapFrame.Create(drawingStream);
                UserImage.Source = b;
            }
            
        }
```
If it's possible , please put full code for getting photo of TLUser.

**Comment by hadi77ir** [comment]
Have you checked that `photo` is not empty?
