### ISSUE TITLE
Error API_ID_INVALID, but the code is correct

### ISSUE THREAD

**Issue by claytonbnu** [sochix/TLSharp#442]
This is the configuration of https://my.telegram.org/apps.

![telegram](https://cloud.githubusercontent.com/assets/13488218/24756146/1d3376be-1ab3-11e7-9a4d-9b43f85115e2.png)

This is the code,  the appId and apiHash is same of configurantion in the https://my.telegram.org/apps:

```cs
using System;
using System.Threading.Tasks;
using TLSharp.Core;

namespace IntegracaoTelegram
{
    class Program
    {        
        const string phoneNumber = "+554799111170";
        const int apiId = 100283;
        const string apiHash = "e1bcXXXXXXXXXXXXXXXXXX908a";

        static void Main(string[] args)
        {
            Service bot = new Service(apiId, apiHash);
            Authenticate(bot).Wait();

            System.Threading.Thread.Sleep(System.Threading.Timeout.Infinite);
        }
           
       static async Task Authenticate(Service bot)
         {
             await bot.Connect();
             await bot.Authenticate(phoneNumber);
         }
    }

    public sealed class Service
    {
        private TelegramClient client;
        private ISessionStore store;
        public Service(int apiId, string apiHash)
        {
            store = new FileSessionStore();
            this.client = new TelegramClient(apiId, apiHash, store);
        }

        public async Task Connect()
        {
            await this.client.ConnectAsync();
        }

        public async Task Authenticate(String phoneNumber)
        {
            var hash = await client.SendCodeRequestAsync(phoneNumber);                     

            Console.WriteLine("Inform the received code from Telegram: ");
            var code = Console.ReadLine(); 

            var user = await client.MakeAuthAsync(phoneNumber, hash, code);

            Console.WriteLine("The UserID is: {0}",user.id);
        }
    }
}
```

And this is the Error!
![error](https://cloud.githubusercontent.com/assets/13488218/24756141/1a5b5506-1ab3-11e7-9a09-a80302d59f12.png)

## What did I do wrong?

**Comment by samuelg78** [comment]
I also experienced the same issue.

**Comment by samuelg78** [comment]
Seems like all new numbers will have this errors due to recently updates of Telegram.

**Comment by knocte** [comment]
Please post the exception, not screenshots. The exception is the text you get when you do `ex.ToString()`

**Comment by samuelg78** [comment]
The exception is "API_ID_INVALID"

**Comment by knocte** [comment]
That's not an exception, that's an error code.

**Comment by an2114** [comment]
Experiencing the same problem for a newly registered dev account. I haven't observed this issue using another account, generated for about two weeks ago. The only noticeable difference between these accounts is that API_ID for the new account contains 6 digits, but previous one - 5.

**Comment by an2114** [comment]
> That's not an exception, that's an error code.
If you are expecting a stack trace, please see below:
`at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<SendCodeRequestAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
  at {my_code}`

**Comment by samuelg78** [comment]
![image](https://cloud.githubusercontent.com/assets/12243527/24792955/a3bfccfa-1bb2-11e7-8530-2a6c4b49eff6.png)

**Comment by knocte** [comment]
To be strict, a stacktrace is only one part of the exception. `ex.ToString()` however includes more things, such as: exception's message, innerException.tostring() (recursively until finding a null innerException), and the exception's stacktrace.

**Comment by an2114** [comment]
ex.ToString() result

System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: API_ID_INVALID
   at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<SendCodeRequestAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TelegramLibrary.TelegramClientWrapper.<Authenticate>d__5.MoveNext() in C:\Devel\...:line 48
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ... my code ...  :line 338
---> (Inner Exception #0) System.InvalidOperationException: API_ID_INVALID
   at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<SendCodeRequestAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TelegramLibrary.TelegramClientWrapper.<Authenticate>d__5.MoveNext() in C:\Devel\...line 48<---

**Comment by samuelg78** [comment]
Hi, able to resolve the issue?

**Comment by astuteficus** [comment]
I have the same

**Comment by astuteficus** [comment]
Works with another AipId (obtained a long time ago). So it's Telegram's issue

**Comment by astuteficus** [comment]
Works with another ApiId (obtained a long time ago). So it's Telegram's issue.

**Comment by samuelg78** [comment]
How to report to telegram? The support is not responding.

**Comment by samuelg78** [comment]
Hi anyone got reply from telegram support?

**Comment by astuteficus** [comment]
I wrote them too several days ago. No answer.

**Comment by samuelg78** [comment]
There's a serious issue with the support.

**Comment by shabahang4u** [comment]
I have same problem with api_id and get no response from telegram support.

**Comment by jak65** [comment]
I have same problem too

**Comment by an2114** [comment]
More than a week have passed since I reported to support (and also to the official support community), but I still haven't received any response.

**Comment by StrangePers** [comment]
I wrote them 5 times for the last 3 months with different issues and from several accounts. They never answered.

**Comment by samuelg78** [comment]
They had just replied that they fixed the problem.

**Comment by an2114** [comment]
Yes, I confirm the issue is fixed
