### ISSUE TITLE
Error Occured: API_ID_INVALID

### ISSUE THREAD

**Issue by lee011** [sochix/TLSharp#478]
Sorry for posting an old issue, but I can't find any significant solution that works for me.

When I try to log in, it always throws API_ID_INVALID error. However, I have checked many times, both the api_id and api_hash are correct.

Code: (Parts of api_hash and phone number has been hidden due to privacy reasons)
````vb
Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
    Dim s As New FileSessionStore
    client = New TelegramClient(126108, "8b7f......b77c", s, "session", New Network.TcpClientConnectionHandler(Function(x As String, y As Integer) As Sockets.TcpClient
                                                                                                                                   Dim tcp = New Sockets.TcpClient
                                                                                                                                   tcp.Connect("149.154.167.40", 443)
                                                                                                                                   Return tcp
                                                                                                                               End Function))
End Sub

Private Async Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
    Try
        Dim r = Await client.ConnectAsync
        If Not client.IsUserAuthorized Then
            Dim h = Await client.SendCodeRequestAsync("+8525xxxxxx1")
            Dim code = Form2.ShowDialog
            If code IsNot Nothing Then
                Dim u = Await client.MakeAuthAsync("+8525xxxxxx1", h, code)
            End If
        End If
        Button1.Enabled = False
    Catch ex As Exception
        MsgBox(ex.ToString, 16, "Telegram API")
    End Try
End Sub
````

Error:
````
System.InvalidOperationException: API_ID_INVALID
   at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<SendCodeRequestAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WindowsApp3.Form1.VB$StateMachine_3_Button1_Click.MoveNext() at C:\Users\Kelvin\documents\visual studio 2017\Projects\WindowsApp3\WindowsApp3\Form1.vb: Line 21
````

**Comment by mehdiyahyavi** [comment]
suggest : 1. store apiID and apiHash to a variable like this : 
C#:
```
private int apiID = 180343;
private string apiHash = "112225e75f5b6f8821de379ab15fc5ac";
```

and use this code : (use only 4 overload)

`client = new TelegramClient(apiID, apiHash, null,"session");``

**Comment by lee011** [comment]
It works! Thanks for your solution.
