### ISSUE TITLE
error in sendmessage or forwardmessage - bug in tlsharp

### ISSUE THREAD

**Issue by mahdivpg** [sochix/TLSharp#508]
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=USER_BANNED_IN_CHANNEL
  Source=TLSharp.Core
  StackTrace:
       at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request) in C:\Users\meytiii\Downloads\z TL Amazing Library\TLSharp-master\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 318
       at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request) in C:\Users\meytiii\Downloads\z TL Amazing Library\TLSharp-master\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 206
       at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext() in C:\Users\meytiii\Downloads\z TL Amazing Library\TLSharp-master\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 144
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at TLSharp.Core.TelegramClient.<SendRequestAsync>d__18`1.MoveNext() in C:\Users\meytiii\Downloads\z TL Amazing Library\TLSharp-master\TLSharp-master\TLSharp.Core\TelegramClient.cs:line 231
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at TLSharp.Core.TelegramClient.<ForwardMessagesAsync>d__21.MoveNext() in C:\Users\meytiii\Downloads\z TL Amazing Library\TLSharp-master\TLSharp-master\TLSharp.Core\TelegramClient.cs:line 280
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at Test.Form1.<button3_Click>d__9.MoveNext() in c:\users\meytiii\documents\visual studio 2015\Projects\Test\Test\Form1.cs:line 125
  InnerException: 

hi guys.

mr sochix bug in tlsharp please fix tnx

**Comment by sochix** [comment]
USER_BANNED_IN_CHANNEL that's the problem
