### ISSUE TITLE
A connection attempt failed

### ISSUE THREAD

**Issue by mostafa8026** [sochix/TLSharp#530]
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 149.154.167.91:443

**Comment by mostafa8026** [comment]
at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
   at TLSharp.Core.Network.TcpTransport..ctor(String address, Int32 port, TcpClientConnectionHandler handler)
   at TLSharp.Core.TelegramClient.<ReconnectToDcAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by mostafa8026** [comment]
149.154.167.91:443

What is this IP?

**Comment by rostyslavternushchak** [comment]
@mostafa8026 just google it....

**City** not provided
**Country** United Kingdom (GB) (99% confidence)
**Continent** Europe (EU)
**Time zone** Europe/London 

**ISPTelegram** Messenger LLP 
**Organization** Telegram Messenger LLP 
**User type** business 
**Autonomous system number (ASN)** 62041 
**Autonomous system organization** Telegram Messenger LLP
