### ISSUE TITLE
throw System.InvalidOperationException ("LIMIT_INVALID")

### ISSUE THREAD

**Issue by esavkin** [sochix/TLSharp#531]
Hello All,

When I try to receive a photo (avatar for different user or channel), the API giving the error: "LIMIT_INVALID"
UnitTest DownloadFileFromWrongLocationTest from TLSharpTests.cs doesn't work too.

Code:
```
var result = await client.GetContactsAsync();
var user = result.users.lists
                .OfType<TLUser>()
                .FirstOrDefault();
    
            var photo = ((TLUserProfilePhoto)user.photo);
            var photoLocation = (TLFileLocation) photo.photo_big;

 var resFile = await client.GetFile(new TLInputFileLocation()
                {
                    local_id = photoLocation.local_id,
                    secret = photoLocation.secret,
                    volume_id = photoLocation.volume_id
                }, 1024);
```

StackTrace:
```
   at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request) in C:\Projects\Telegramm\TLSharp.lib\TLSharp.Core\Network\MtProtoSender.cs:line 318
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request) in C:\Projects\Telegramm\TLSharp.lib\TLSharp.Core\Network\MtProtoSender.cs:line 206
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext() in C:\Projects\Telegramm\TLSharp.lib\TLSharp.Core\Network\MtProtoSender.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<SendRequestAsync>d__18`1.MoveNext() in C:\Projects\Telegramm\TLSharp.lib\TLSharp.Core\TelegramClient.cs:line 231
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<GetFile>d__25.MoveNext() in C:\Projects\Telegramm\TLSharp.lib\TLSharp.Core\TelegramClient.cs:line 315
```

**Comment by esavkin** [comment]
Issue solved: I changed filePartSize to 1024 * 32 - it works

var resFile = await client.GetFile(new TLInputFileLocation()
                {
                    local_id = photoLocation.local_id,
                    secret = photoLocation.secret,
                    volume_id = photoLocation.volume_id
                }, **1024 * 32**);

**Comment by mahyarff** [comment]
#https://github.com/sochix/TLSharp/issues/557#issuecomment-342606822
