### ISSUE TITLE
ConnectAsync throws Can't decode packet

### ISSUE THREAD

**Issue by sergey-rush** [sochix/TLSharp#551]
While trying to connect I get the error Can't decode packet. Stack trace is below:
   at TLSharp.Core.Network.MtProtoSender.DecodeMessage(Byte[] body)
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<ConnectAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TelegramClientWinForm.MainForm.<SendMessage>d__4.MoveNext() in C:\TelegramClient\MainForm.cs:line 64

**Comment by KutuevVladimir** [comment]
I have the same problem.

**Comment by mahdivpg** [comment]
I have the same problem!

**Comment by darkusone** [comment]
I was have the same yesterday, maybe you was using a Demo server and maybe you have a store.dat file for these session, try deleting this file and any .dat on your debug/release/bin folder where is running your app 

And so important, open Visual Studio as Administrator before sending AuthMessage on API Login
