### ISSUE TITLE
Unable to cast object of type 'TeleSharp.TL.Auth.TLCheckedPhone' to type 'TeleSharp.TL.Contacts.TLAbsContacts'.

### ISSUE THREAD

**Issue by mostafa8026** [sochix/TLSharp#556]
My code:
//get available contacts
                var result = await Client.GetContactsAsync();

                //find recipient in contacts
                var user = result.users.lists
                    .Where(x => x.GetType() == typeof(TLUser))
                    .Cast<TLUser>()
                    .FirstOrDefault(x => x.phone == mobile);

Unable to cast object of type 'TeleSharp.TL.Auth.TLCheckedPhone' to type 'TeleSharp.TL.Contacts.TLAbsContacts'.
   at TeleSharp.TL.Contacts.TLRequestGetContacts.deserializeResponse(BinaryReader br)
   at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<SendRequestAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<GetContactsAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CNPR.Telegram.TelegramClass.<FindUser>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at smsManager.frmTelegramSendReceive.<SendTelegramyarText>d__47.MoveNext()

**Comment by knocte** [comment]
Seems like a TLSharp bug. You're welcome to submit a PullRequest to fix it. Thanks
