### ISSUE TITLE
NETWORK_MIGRATE error using SendCodeRequestAsync

### ISSUE THREAD

**Issue by dvygolov** [sochix/TLSharp#568]
I need to sign up in Telegram with a brand new phone number.
So, I've tried to use this code snippet from TLSharp tests:
```
            var client = NewClient();
            await client.ConnectAsync();
            var hash = await client.SendCodeRequestAsync(NotRegisteredNumberToSignUp);
            var code = "";

            var registeredUser = await client.SignUpAsync(NotRegisteredNumberToSignUp, hash, code, "TLSharp", "User");
            Assert.IsNotNull(registeredUser);
            Assert.IsTrue(client.IsUserAuthorized());

            var loggedInUser = await client.MakeAuthAsync(NotRegisteredNumberToSignUp, hash, code);
            Assert.IsNotNull(loggedInUser);
```

but on the third line a NETWORK_MIGRATE_2 Exception is thrown. I've tried this with different numbers but with no success.

Here's the stacktrace.

```
   at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<SendCodeRequestAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TelegramSender.Services.TelegramService.<SendRequestCode>d__5.MoveNext() in C:\Programming\Git\Freelance\TelegramSender\TelegramSender\Services\TelegramService.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TelegramSender.MainService.<GetNewNumberAndRegisterItInTelegram>d__7.MoveNext() in C:\Programming\Git\Freelance\TelegramSender\TelegramSender\MainService.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TelegramSender.MainService.<Process>d__6.MoveNext() in C:\Programming\Git\Freelance\TelegramSender\TelegramSender\MainService.cs:line 75
```

**Comment by dvygolov** [comment]
As a workaround I had to download sources and change in TelegramClient.cs the ReconnectToDcAsync method from private to public and then to use smth like this:
```
            try
            {
                hash = await _client.SendCodeRequestAsync(phoneNumber);
            }
            catch (Exception e)
            {
                if (e.Message == "NETWORK_MIGRATE_2")
                    await _client.ReconnectToDcAsync(2);
                hash = await _client.SendCodeRequestAsync(phoneNumber);
            }
```

**Comment by knocte** [comment]
Hi @dvygolov ! Thanks for reporting this bug.

If we want to fix this inside TLSharp, the approach should be:
- Create MigrationException class with a `int DataCenter` property, inheriting System.Exception.
- Create NetworkMigrationException class which inherits from MigrationException.
- Make existing PhoneMigrationException inherit from MigrationException.
- Catch the NETWORK_MIGRATE_* error in MtProtoSender class, in the same way the PhoneMigrationException is created. (Around https://github.com/sochix/TLSharp/blob/ca6e18b50ea7cab777ae0a49e1a7097dc1ae2583/TLSharp.Core/Network/MtProtoSender.cs#L290 ).
- Change all PhoneMigrationException catch clauses in TelegramClient.cs to catch MigrationException instead.

It would be great if you could propose the apprach above as a new PullRequest!
Thanks

**Comment by dvygolov** [comment]
I've done it a bit differently from your proposal, but it works good :-)
#576

**Comment by knocte** [comment]
Thanks! I gave a quick review, let me know when you update the PR.
