### ISSUE TITLE
Unhandled UserMigrationException

### ISSUE THREAD

**Issue by arayeji** [sochix/TLSharp#599]
TLSharp.Core.Network.UserMigrationException: User located on a different DC: 4. See: https://github.com/sochix/TLSharp#i-get-a-xxxmigrationexception-or-a-migrate_x-error
   at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<SendRequestAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<GetContactsAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TelegramDesktopClient.Main.<Form1_Load>d__2.MoveNext() in

**Comment by Grepsy** [comment]
Actually it can handle these migrations, it's implemented as an `DataCenterMigrationException` which can be caught like here: https://github.com/sochix/TLSharp/blob/0015cf494bea2edce13be36665f177574edadac1/TLSharp.Core/TelegramClient.cs#L148

I believe this logic for handling this exception should be used at the other methods that use `_sender.Send(request);` as well. Maybe in `SendRequestAsync<T>` makes sense as that covers most methods. But I'm not familiar with the code enough to make that decision.

**Comment by knocte** [comment]
What exact method were you using @arayeji? As @Grepsy already hints, maybe we just need to catch DataCenterMigrationException (instead of just PhoneMigrationException) everywhere. Similar to what @vygolov did here: https://github.com/sochix/TLSharp/commit/0015cf494bea2edce13be36665f177574edadac1

**Comment by Grepsy** [comment]
I believe this issue can be closed.

**Comment by knocte** [comment]
Yes, fixed in https://github.com/Grepsy/TLSharp/commit/129e319068b6c83b510a2f3be3b07eeab0bc2c74 , thanks.

**Comment by knocte** [comment]
I meant https://github.com/sochix/TLSharp/commit/3ba3ea53fde4a61fdeed01f3b75d2db8007875f7

**Comment by moslem7026** [comment]
i have infinit loop on  `await ReconnectToDcAsync(e.DC);`  and 
`Exception thrown: 'TLSharp.Core.Network.UserMigrationException' in TLSharp.Core.dll
Exception thrown: 'TLSharp.Core.Network.UserMigrationException' in mscorlib.dll` error in outpu

**Comment by knocte** [comment]
@moslem7026 are you using latest git master branch?

**Comment by moslem7026** [comment]
yes , i used both version (nuget Package ) and source file from master branch . both of them i  have problem .

**Comment by mvardin** [comment]
Hi , i got the same ...
in **ReconnectToDcAsync** method , i got the loop with same dc ...
its occurs after getting file , before getting file , its works but after getting file , its got loop in ReconnectToDcAsync

i try to read same problem of issues and unfortunately can not find any solution 
i try both nuget dll and source code , both is the same

**USER_MIGRATE_1**

this is final error i got from telegram ...
not stack trace , just got errorCode 303 and  errorMessage USER_MIGRATE_1

any idea or solution would be appropriate 
thanks

**Comment by ehsanasgarian** [comment]
i have this problem too. this will be solve by delete session and re-login

**Comment by mvardin** [comment]
Thanks for your replay
yes , i try it out but after getting file , this problem has been occur again ...
any other solution?
