### ISSUE TITLE
IsConnected is always true

### ISSUE THREAD

**Issue by deadmann** [sochix/TLSharp#645]
assume i use the following code:

```
        private async Task<TelegramClient> NewClient()
        {
            try
            {

                if (_client == null)
                    _client = new TelegramClient(_apiId, _apiHash, _sessionStore);
                if (!_client.IsConnected)
                    await _client.ConnectAsync();

                return _client;
            }
            catch (MissingApiConfigurationException ex)
            {
                throw new Exception($"Please add your API settings to the `app.config` file. (More info: {MissingApiConfigurationException.InfoUrl})",
                    ex);
            }
        }
```

When it enter the state in which the `_client` is `null`, i create a new instance of the client...
so after that i check for `IsConnected`, so if the session was existed and it somehow got disconnected, i do a reconnecting process, but the issue is it always return `true` as the value of `_client.IsConnected` so the code won't run and any action afterward generates exception, or it make it to run all the time.

**Comment by AskoldMakaruk** [comment]
Have  the same problem.

**Comment by knocte** [comment]
Thanks for reporting this bug guys.

I've tried to write a fix for this, but not sure if it's correct.

Do you guys mind applying it on your gitclones and test it? Here it is: https://gist.github.com/anonymous/305241f672730667807a37193f8ea859

**Comment by AskoldMakaruk** [comment]
@knocte Seems it fix it, but I'm not sure, didn't use it enough. Can you update NuGet package?

**Comment by deadmann** [comment]
Please notify us when you push the changes

**Comment by knocte** [comment]
@deadmann can you test the proposed fix first, to see if you reproduce the same problem as @AskoldMakaruk ?

**Comment by deadmann** [comment]
i try

**Comment by deadmann** [comment]
this is when ok when private sender field is not null...
Note: i wait for the program somethime in debug mode right before it connects, and it become like: IsConnected=>false

```
if (_client == null)
                    _client = new TelegramClient(_apiId, _apiHash, _sessionStore);
#warning IsConnected ==> Always TRUE
                //if (!_client.IsConnected)
                    await _client.ConnectAsync();

                return _client;
```
so i continue the code, no matter how many time it goes to the _client.ConnectAsync, it never got reconnected (i'm not sure if the state said disconnect, but on finding user which is the next TLSharp method i call, the client generated errors), i tried to reproduce the error, but it didn't get disconnected again

**Comment by knocte** [comment]
I'm having a hard time understanding your message. `this is when ok when private sender field is not null...`? I cannot parse that.

**Comment by deadmann** [comment]
sorry, i edit... sometime my hand and my mind are not in sync :D it's myMind.InvokeRequired==true, but the thread fails...

**Comment by knocte** [comment]
> while it generate errors afterward...

I guess you mean exceptions, not errors. Please paste every exception as text (not screenshot), including whole stack trace.

**Comment by deadmann** [comment]
Message: One or more errors occurred.
Stack: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at TelegramReportingService.TelegramReportingManager.Runner(Object state) in C:\Users\Hassan\Documents\Visual Studio 2015\Projects\Reporting\TelegramReportingService\TelegramReportingManager.cs:line 236

Inner:
  Message:
  Object reference not set to an instance of an object.
  Stack:
     at TLSharp.Core.TelegramClient.<RequestWithDcMigration>d__11.MoveNext() in F:\Hassan\Git Repository\TLSharp\TLSharp\TLSharp.Core\TelegramClient.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TLSharp.Core.TelegramClient.<SendRequestAsync>d__19`1.MoveNext() in F:\Hassan\Git Repository\TLSharp\TLSharp\TLSharp.Core\TelegramClient.cs:line 223
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TLSharp.Core.TelegramClient.<GetContactsAsync>d__20.MoveNext() in F:\Hassan\Git Repository\TLSharp\TLSharp\TLSharp.Core\TelegramClient.cs:line 237
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TelegramReportingService.Helper.TelegramHelper.<FindUserByPhoneNumber>d__8.MoveNext() in C:\Users\Hassan\Documents\Visual Studio 2015\Projects\Reporting\TelegramReportingService\Helper\TelegramHelper.cs:line 87

    Inner: NULL

**Comment by Trinitron** [comment]
R0.1.0.386 is avalable and i still have no idea why **IsUserAuthorized** checks sessionStore existence. how to check connection state then?

**Comment by knocte** [comment]
hey guys, it seems someone has made a PR to fix this bug: https://github.com/sochix/TLSharp/pull/927 can any of you test it?
