### ISSUE TITLE
ConnectAsync: 'Client not connected to server.'

### ISSUE THREAD

**Issue by AskoldMakaruk** [sochix/TLSharp#653]
Every time before I send message I have code like this: `if(!IsConnected)
                await ConnectAsync();`
Its throw System.InvalidOperationException in line with ConnectAsync.

**Comment by knocte** [comment]
InvalidOperationException is only the type name of the exception. Can you give more details? What's the exception message? And paste the whole stack trace please.

**Comment by AskoldMakaruk** [comment]
@knocte 
Message :Once the socket has been disconnected, you can only reconnect again asynchronously, and only to a different EndPoint.  BeginConnect must be called on a thread that won't exit until the operation has been completed.
 Stacktrace:    at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
   at TLSharp.Core.Network.TcpTransport.<Send>d__5.MoveNext() in C:\Users\Askold\Desktop\TLSharp-master\TLSharp.Core\Network\TcpTransport.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TLSharp.Core.Network.MtProtoSender.<Send>d__7.MoveNext() in C:\Users\Askold\Desktop\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TLSharp.Core.Network.MtProtoSender.<Send>d__6.MoveNext() in C:\Users\Askold\Desktop\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TLSharp.Core.TelegramClient.<ConnectAsync>d__9.MoveNext() in C:\Users\Askold\Desktop\TLSharp-master\TLSharp.Core\TelegramClient.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at BotChatWarsConsole.Accaunt.<AllTimerHandlerAsync>d__13.MoveNext() in C:\Users\Askold\Source\Repos\BotChatWarsConsole2\BotChatWarsConsole\Accaunt.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by knocte** [comment]
Can you update to latest git master and check if this still happens? If it does, paste the whole exception, i.e. what you get from `ex.ToString()` thanks.

**Comment by knocte** [comment]
This might actually because we have a bug around IsConnected:
https://github.com/sochix/TLSharp/issues/645
So if your code tries to run the connection in parallel with other threads which are already connected, it might explode...
So I'm closing this as a duplicate.
