### ISSUE TITLE
How do I out of my account?

### ISSUE THREAD

**Issue by alish123456** [sochix/TLSharp#657]
hi
Can you help me out of my account (session)? 

`            TLRequestLogOut trlo = new TLRequestLogOut();
            TLUpdates tlu = await client.SendRequestAsync<TLUpdates>(trlo);`

The above code does not work :|

**Comment by knocte** [comment]
Are you really a developer? "does not work" is the worst possible way to report a bug. Please please please give more details. Do you get an exception? Does it hang? WHAT??

**Comment by aeria677** [comment]
I get similar problem when trying to sign out, I get InvalidOperationException.
This is my code:
`TLRequestLogOut logout = new TLRequestLogOut();
bool result = await client.SendRequestAsync(Of Boolean)(logout);`

and the stacktrace:

`Exception thrown: 'System.InvalidOperationException' in tlsharp.dll
   at TLSharp.Core.Network.TcpTransport.Receieve() in TeleSharp.Core\Network\TcpTransport.cs:line 45
   at TLSharp.Core.Network.MtProtoSender.Receive(TLMethod request) in TeleSharp.Core\Network\MtProtoSender.cs:line 139
   at TLSharp.Core.TelegramClient.RequestWithDcMigration(TLMethod request) in TeleSharp.Core\TelegramClient.cs:line 123
   at TLSharp.Core.TelegramClient.SendRequestAsync[T](TLMethod methodToExecute) in TeleSharp.Core\TelegramClient.cs:line 226
   at MyTelegram.TelegramClient.Logout() in TelegramClient.cs:line 116`

any solutions?

**Comment by knocte** [comment]
> I get similar problem when trying to sign out, I get
InvalidOperationException.

@aeria677 thanks for telling us about your InvalidOperationException and
pasting the stacktrace, but what is the exception message?

**Comment by aeria677** [comment]
I get similar problem when trying to sign out, I get InvalidOperationException. 

This is my code:
TLRequestLogOut signout = new TLRequestLogOut();
var upd = client.SendRequestAsync(Of TLUpdates)(signout);

and the stacktrace:
`Exception thrown: 'System.InvalidOperationException' in tlsharp.dll at TLSharp.Core.Network.TcpTransport.Receieve() in TeleSharp.Core\Network\TcpTransport.cs:line 45 at TLSharp.Core.Network.MtProtoSender.Receive(TLMethod request) in TeleSharp.Core\Network\MtProtoSender.cs:line 139 at TLSharp.Core.TelegramClient.RequestWithDcMigration(TLMethod request) in TeleSharp.Core\TelegramClient.cs:line 123 at TLSharp.Core.TelegramClient.SendRequestAsync[T](TLMethod methodToExecute) in TeleSharp.Core\TelegramClient.cs:line 226 at MyTelegram.TelegramClient.Logout() in TelegramClient.cs:line 116`

I have try to debug it. and the error is at TcpTransport.cs at line 44 at function:
`public TcpMessage Receieve()`

This code is marked: 
`if (stream.Read(packetLengthBytes, 0, 4) != 4)`

And the exception message is:
System.IO.IOException
Additional information: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine.

**Comment by knocte** [comment]
Does it happens always, 100% of the times you test it? Or only sometimes?

**Comment by aeria677** [comment]
Yes, I always get this System.InvalidOperationException

**Comment by knocte** [comment]
In your previous comment you said it's an IOException, which one is it? InvalidOperationException or IOException?

**Comment by aeria677** [comment]
I always get InvalidOperationException, but sometimes I get System.IO.IOException too. Maybe the System.IO.IOException is caused by I do sign out quickly after the sign in is success...

**Comment by knocte** [comment]
* For the InvalidOperationException you have provided the stacktrace but not the exception message.
* For the IOException you have provided the exception message but not the stacktrace.

Please complete this information.

**Comment by aeria677** [comment]
For the InvalidOperationException the exception message is Couldn't read the packet length

**Comment by aeria677** [comment]
For the IOException

```
   at TLSharp.Core.Network.TcpTransport.Receieve() in TeleSharp.Core\Network\TcpTransport.cs:line 45
   at TLSharp.Core.Network.MtProtoSender.Receive(TLMethod request) in TeleSharp.Core\Network\MtProtoSender.cs:line 139
   at TLSharp.Core.TelegramClient.RequestWithDcMigration(TLMethod request) in TeleSharp.Core\TelegramClient.cs:line 128
   at TLSharp.Core.TelegramClient.SendRequestAsync[T](TLMethod methodToExecute) in TeleSharp.Core\TelegramClient.cs:line 236
```

**Comment by alish123456** [comment]
Did not find the correct answer?
I need logout of my account.
My problem are similar to the ones above.

**Comment by karimzzzm** [comment]
Why no one answers the question؟
I also want to leave the telegram account
Give a sample code that goes out of the Telegram account

**Comment by karimzzzm** [comment]
Help us

**Comment by karimzzzm** [comment]
@knocte  Help us

**Comment by knocte** [comment]
If there is no answer it means that we don't know the answer. TLSharp is a library developed by the community, whenever a developer finds a problem in TLSharp, they try to fix it, and if they succeed, they propose a PullRequest so that everyone benefits. Welcome to open source :)
