### ISSUE TITLE
msg_id too low...

### ISSUE THREAD

**Issue by deadmann** [sochix/TLSharp#668]
Starting 2 Hour Ago, i'm receiving an exception. 
_msg_seqno too low (the server has already received a message with a lower msg_id but with either a higher or an equal and odd seqno)_

   at TLSharp.Core.Network.MtProtoSender.HandleBadMsgNotification(UInt64 messageId, Int32 sequence, BinaryReader messageReader)
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<ConnectAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TelegramAdvertiser.Helper.TelegramHelper.<NewClientAsync>d__12.MoveNext() in C:\Users\Hassan\Documents\Visual Studio 2015\Projects\Advertiser\TelegramAdvertiser\Helper\TelegramHelper.cs:line 161
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TelegramAdvertiser.Helper.TelegramHelper.<FindUserByPhoneNumberAsync>d__8.MoveNext() in C:\Users\Hassan\Documents\Visual Studio 2015\Projects\Advertiser\TelegramAdvertiser\Helper\TelegramHelper.cs:line 64

 1. looking at telegram website, it seem the time is not in sync, but my computer sync from internet...
 2. looking at another, seem session may get expire, i tried to recreate, but it again need connecting, and same error appear...

what should i do?

thank you,
Hassan F.

**Comment by mahdivpg** [comment]
hi 
Delete the session
Log in again

**Comment by deadmann** [comment]
it again worked today, and stop working wholy the next time...
how am i suppose to delete the session when it generate error on connect?

**Comment by mbj2007** [comment]
hi,
i use this code i create it from https://github.com/LonamiWebs/Telethon/blob/master/telethon/network/mtproto_sender.py
but some time it is not working

`private bool HandleBadMsgNotification(ulong messageId, int sequence, BinaryReader messageReader, TeleSharp.TL.TLMethod request)
        {
            uint code = messageReader.ReadUInt32();
            ulong requestId = messageReader.ReadUInt64();
            int requestSequence = messageReader.ReadInt32();
            int errorCode = messageReader.ReadInt32();

            switch (errorCode)
            {
                case 16:
                    _session.UpdateOffset((long)messageId);
                    var t1 = Send(request);
                    t1.Wait();
                    break;
                //throw new InvalidOperationException("msg_id too low (most likely, client time is wrong; it would be worthwhile to synchronize it using msg_id notifications and re-send the original message with the “correct” msg_id or wrap it in a container with a new msg_id if the original message had waited too long on the client to be transmitted)");
                case 17:
                    _session.UpdateOffset((long)messageId);
                    var t2 = Send(request);
                    t2.Wait();
                    break;
                //throw new InvalidOperationException("msg_id too high (similar to the previous case, the client time has to be synchronized, and the message re-sent with the correct msg_id)");
                case 18:
                    throw new InvalidOperationException("incorrect two lower order msg_id bits (the server expects client message msg_id to be divisible by 4)");
                case 19:
                    throw new InvalidOperationException("container msg_id is the same as msg_id of a previously received message (this must never happen)");
                case 20:
                    throw new InvalidOperationException("message too old, and it cannot be verified whether the server has received a message with this msg_id or not");
                case 32:
                    _session.Sequence += 64;
                    var t3 = Send(request);
                    t3.Wait();
                    break;
                    //throw new InvalidOperationException("msg_seqno too low (the server has already received a message with a lower msg_id but with either a higher or an equal and odd seqno)");
                case 33:
                    _session.Sequence -= 16;
                    var t4=Send(request);
                    t4.Wait();
                    break;
                // throw new InvalidOperationException(" msg_seqno too high (similarly, there is a message with a higher msg_id but with either a lower or an equal and odd seqno)");
                case 34:
                   
                    throw new InvalidOperationException("an even msg_seqno expected (irrelevant message), but odd received");
                case 35:
                    throw new InvalidOperationException("odd msg_seqno expected (relevant message), but even received");
                case 48:
                    throw new InvalidOperationException("incorrect server salt (in this case, the bad_server_salt response is received with the correct salt, and the message is to be re-sent with it)");
                case 64:
                    throw new InvalidOperationException("invalid container");

            }
            throw new NotImplementedException("This should never happens");
            /*
			logger.debug("bad_msg_notification: msgid {0}, seq {1}, errorcode {2}", requestId, requestSequence,
						 errorCode);
			*/
            /*
			if (!runningRequests.ContainsKey(requestId))
			{
				logger.debug("bad msg notification on unknown request");
				return true;
			}
			*/

            //OnBrokenSessionEvent();
            //MTProtoRequest request = runningRequests[requestId];
            //request.OnException(new MTProtoBadMessageException(errorCode));

            return true;
        }`

**Comment by mahdivpg** [comment]
سلام mbj2007 
اگر امکانش هست خواهشا یا ایمیل یا آیدی تلگرامتون رو بدید کار واجب دارم باهاتون ممنون

**Comment by NaderStar** [comment]
he is not from iran
share your telegram user name

**Comment by mahdivpg** [comment]
@TlgramApi

**Comment by knocte** [comment]
@deadmann were you sending more than one request at the same time?

**Comment by hanigamini** [comment]
@mbj2007 
Hi,
Can you explain about UpdateOffset in your code?
_session.UpdateOffset((long)messageId);

**Comment by WatchDogsDev** [comment]
Any solution for this ?

**Comment by yAnn1ck-B** [comment]
> hi,
> i use this code i create it from https://github.com/LonamiWebs/Telethon/blob/master/telethon/network/mtproto_sender.py
> but some time it is not working
> 
> `private bool HandleBadMsgNotification(ulong messageId, int sequence, BinaryReader messageReader, TeleSharp.TL.TLMethod request)
> {
> uint code = messageReader.ReadUInt32();
> ulong requestId = messageReader.ReadUInt64();
> int requestSequence = messageReader.ReadInt32();
> int errorCode = messageReader.ReadInt32();
> 
> ```
>         switch (errorCode)
>         {
>             case 16:
>                 _session.UpdateOffset((long)messageId);
>                 var t1 = Send(request);
>                 t1.Wait();
>                 break;
>             //throw new InvalidOperationException("msg_id too low (most likely, client time is wrong; it would be worthwhile to synchronize it using msg_id notifications and re-send the original message with the “correct” msg_id or wrap it in a container with a new msg_id if the original message had waited too long on the client to be transmitted)");
>             case 17:
>                 _session.UpdateOffset((long)messageId);
>                 var t2 = Send(request);
>                 t2.Wait();
>                 break;
>             //throw new InvalidOperationException("msg_id too high (similar to the previous case, the client time has to be synchronized, and the message re-sent with the correct msg_id)");
>             case 18:
>                 throw new InvalidOperationException("incorrect two lower order msg_id bits (the server expects client message msg_id to be divisible by 4)");
>             case 19:
>                 throw new InvalidOperationException("container msg_id is the same as msg_id of a previously received message (this must never happen)");
>             case 20:
>                 throw new InvalidOperationException("message too old, and it cannot be verified whether the server has received a message with this msg_id or not");
>             case 32:
>                 _session.Sequence += 64;
>                 var t3 = Send(request);
>                 t3.Wait();
>                 break;
>                 //throw new InvalidOperationException("msg_seqno too low (the server has already received a message with a lower msg_id but with either a higher or an equal and odd seqno)");
>             case 33:
>                 _session.Sequence -= 16;
>                 var t4=Send(request);
>                 t4.Wait();
>                 break;
>             // throw new InvalidOperationException(" msg_seqno too high (similarly, there is a message with a higher msg_id but with either a lower or an equal and odd seqno)");
>             case 34:
>                
>                 throw new InvalidOperationException("an even msg_seqno expected (irrelevant message), but odd received");
>             case 35:
>                 throw new InvalidOperationException("odd msg_seqno expected (relevant message), but even received");
>             case 48:
>                 throw new InvalidOperationException("incorrect server salt (in this case, the bad_server_salt response is received with the correct salt, and the message is to be re-sent with it)");
>             case 64:
>                 throw new InvalidOperationException("invalid container");
> 
>         }
>         throw new NotImplementedException("This should never happens");
>         /*
> 		logger.debug("bad_msg_notification: msgid {0}, seq {1}, errorcode {2}", requestId, requestSequence,
> 					 errorCode);
> 		*/
>         /*
> 		if (!runningRequests.ContainsKey(requestId))
> 		{
> 			logger.debug("bad msg notification on unknown request");
> 			return true;
> 		}
> 		*/
> 
>         //OnBrokenSessionEvent();
>         //MTProtoRequest request = runningRequests[requestId];
>         //request.OnException(new MTProtoBadMessageException(errorCode));
> 
>         return true;
>     }`
> ```

This worked pretty well, however I also commented out the "This should never hapen!" error and just return true

**Comment by n3nikita** [comment]
Got the same error. Any help?

**Comment by n3nikita** [comment]
> hi,
> i use this code i create it from https://github.com/LonamiWebs/Telethon/blob/master/telethon/network/mtproto_sender.py
> but some time it is not working
> 
> `private bool HandleBadMsgNotification(ulong messageId, int sequence, BinaryReader messageReader, TeleSharp.TL.TLMethod request)
> {
> uint code = messageReader.ReadUInt32();
> ulong requestId = messageReader.ReadUInt64();
> int requestSequence = messageReader.ReadInt32();
> int errorCode = messageReader.ReadInt32();
> 
> ```
>         switch (errorCode)
>         {
>             case 16:
>                 _session.UpdateOffset((long)messageId);
>                 var t1 = Send(request);
>                 t1.Wait();
>                 break;
>             //throw new InvalidOperationException("msg_id too low (most likely, client time is wrong; it would be worthwhile to synchronize it using msg_id notifications and re-send the original message with the “correct” msg_id or wrap it in a container with a new msg_id if the original message had waited too long on the client to be transmitted)");
>             case 17:
>                 _session.UpdateOffset((long)messageId);
>                 var t2 = Send(request);
>                 t2.Wait();
>                 break;
>             //throw new InvalidOperationException("msg_id too high (similar to the previous case, the client time has to be synchronized, and the message re-sent with the correct msg_id)");
>             case 18:
>                 throw new InvalidOperationException("incorrect two lower order msg_id bits (the server expects client message msg_id to be divisible by 4)");
>             case 19:
>                 throw new InvalidOperationException("container msg_id is the same as msg_id of a previously received message (this must never happen)");
>             case 20:
>                 throw new InvalidOperationException("message too old, and it cannot be verified whether the server has received a message with this msg_id or not");
>             case 32:
>                 _session.Sequence += 64;
>                 var t3 = Send(request);
>                 t3.Wait();
>                 break;
>                 //throw new InvalidOperationException("msg_seqno too low (the server has already received a message with a lower msg_id but with either a higher or an equal and odd seqno)");
>             case 33:
>                 _session.Sequence -= 16;
>                 var t4=Send(request);
>                 t4.Wait();
>                 break;
>             // throw new InvalidOperationException(" msg_seqno too high (similarly, there is a message with a higher msg_id but with either a lower or an equal and odd seqno)");
>             case 34:
>                
>                 throw new InvalidOperationException("an even msg_seqno expected (irrelevant message), but odd received");
>             case 35:
>                 throw new InvalidOperationException("odd msg_seqno expected (relevant message), but even received");
>             case 48:
>                 throw new InvalidOperationException("incorrect server salt (in this case, the bad_server_salt response is received with the correct salt, and the message is to be re-sent with it)");
>             case 64:
>                 throw new InvalidOperationException("invalid container");
> 
>         }
>         throw new NotImplementedException("This should never happens");
>         /*
> 		logger.debug("bad_msg_notification: msgid {0}, seq {1}, errorcode {2}", requestId, requestSequence,
> 					 errorCode);
> 		*/
>         /*
> 		if (!runningRequests.ContainsKey(requestId))
> 		{
> 			logger.debug("bad msg notification on unknown request");
> 			return true;
> 		}
> 		*/
> 
>         //OnBrokenSessionEvent();
>         //MTProtoRequest request = runningRequests[requestId];
>         //request.OnException(new MTProtoBadMessageException(errorCode));
> 
>         return true;
>     }`
> ```

Where should I put this error handler? How can I get `messageId`, `sequence` and etc.?
