### ISSUE TITLE
I get a xxxMigrationException or a MIGRATE_X error!

### ISSUE THREAD

**Issue by mostafa8026** [sochix/TLSharp#677]
at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request) in D:\projects\TLSharp\TLSharp.Core\Network\MtProtoSender.cs:line 294
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request) in D:\projects\TLSharp\TLSharp.Core\Network\MtProtoSender.cs:line 206
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext() in D:\projects\TLSharp\TLSharp.Core\Network\MtProtoSender.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<SendCodeRequestAsync>d__13.MoveNext() in D:\projects\TLSharp\TLSharp.Core\TelegramClient.cs:line 144

**Comment by knocte** [comment]
@mostafa8026 are you using latest git master branch?

**Comment by mostafa8026** [comment]
You know, It loops forever and can't find dc!

**Comment by knocte** [comment]
@mostafa8026 again, are you using latest git master branch?

**Comment by mostafa8026** [comment]
Yes, I am.
Recently, added IP and port to the constructor of my TelegramClient and this error happens.

**Comment by knocte** [comment]
So it happens only on your fork?

**Comment by mostafa8026** [comment]
I delete my fork and use Nuget package. Still same error.

**Comment by knocte** [comment]
I don't know which version is in Nuget, sorry. Please test with master branch.

**Comment by mostafa8026** [comment]
After deleting the session.dat file and rebasing on the last master branch, problem resolved.
