### ISSUE TITLE
Exception on ImportContact

### ISSUE THREAD

**Issue by delphiassistant** [sochix/TLSharp#7]
Hi.
I successfully passed AuthUser Test. Problem was the server ip which is solved by setting server address to 149.154.167.91 .
Now when debugging ImportContact test i get following exception:

Test method TLSharp.Tests.NotificatioClientTests.ImportContact threw exception: 

System.InvalidCastException: Unable to cast object of type 'TLSharp.Core.MTProto.UserSelfConstructor' to type 'TLSharp.Core.MTProto.UserContactConstructor'.

**Comment by sochix** [comment]
It's because you trying to send message to yourself. Select another contact

**Comment by nezam1** [comment]
hi
I run successfully TestConnection and AutenticationWorks but importContact failed 
Test Name:	ImportContact
Test FullName:	TLSharp.Tests.NotificatioClientTests.ImportContact
Test Source:	c:\Users\Androidi\Documents\Bluetooth Folder\TLSharp-master\TLSharp-master\TLSharp.Tests\NotificatioClientTests.cs : line 83
Test Outcome:	Failed
Test Duration:	0:00:01.8068483

Result Message:	
Test method TLSharp.Tests.NotificatioClientTests.ImportContact threw exception: 
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
Result StackTrace:	
at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt64()
   at TLSharp.Core.Network.MtProtoSender.DecodeMessage(Byte[] body) in c:\Users\Androidi\Documents\Bluetooth Folder\TLSharp-master\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 107
   at TLSharp.Core.Network.MtProtoSender.<Recieve>d__f.MoveNext() in c:\Users\Androidi\Documents\Bluetooth Folder\TLSharp-master\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<Connect>d__0.MoveNext() in c:\Users\Androidi\Documents\Bluetooth Folder\TLSharp-master\TLSharp-master\TLSharp.Core\TelegramClient.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Tests.NotificatioClientTests.<ImportContact>d__15.MoveNext() in c:\Users\Androidi\Documents\Bluetooth Folder\TLSharp-master\TLSharp-master\TLSharp.Tests\NotificatioClientTests.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

app.config. is
<configuration>
  <appSettings>
    <add key="numberToAuthenticate" value="+989189996720" />
    <add key="registeredNumber" value="+989189996720" /> 
    <add key="unregisteredNumber" value="+989186683817" />
  </appSettings>
</configuration>

what creat new contactUser and send message to?
