### ISSUE TITLE
A connection attempt failed because...

### ISSUE THREAD

**Issue by sara20189** [sochix/TLSharp#709]
hi.
good timing
when i send message by tlsharp, i get below error.
why?

error message:
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 91.108.4.182:443

please help me...

**Comment by hanigamini** [comment]
Hi,
I have same error sometimes!

**Comment by knocte** [comment]
This might be because your internet connection is not working at that moment. Can you guys share the whole (ex.ToString()) please.

**Comment by hanigamini** [comment]
Thanks @knocte 
Error text : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 91.108.4.182:443

Is there any way to increase time out ? where of code ?

**Comment by knocte** [comment]
I said `ex.ToString()` which means it should include the stacktrace as well.

**Comment by hanigamini** [comment]
@knocte 
I dont have ex.ToString() now.
I returned ex.message.

**Comment by knocte** [comment]
Change your code to print `ex.ToString()` and when you get it again, come here to paste it please.

**Comment by hanigamini** [comment]
@knocte 
Ok,
Thanks

**Comment by hanigamini** [comment]
@knocte 
One of my ex.ToString() , what is the reason?

System.InvalidOperationException: Couldn't read the packet length
   at TLSharp.Core.Network.TcpTransport.<Receieve>d__4.MoveNext()

**Comment by knocte** [comment]
That's only one line of the stack trace, please paste EVERYTHING.

**Comment by hanigamini** [comment]
Constructor Invalid Or Context.Init Not Called ! : System.IO.InvalidDataException: Constructor Invalid Or Context.Init Not Called ! ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TeleSharp.TL.TLContext.getType(Int32 Constructor) in TLSharp-master\TeleSharp.TL\TLContext.cs:line 27
   at TeleSharp.TL.ObjectUtils.DeserializeObject(BinaryReader reader) in TLSharp-master\TeleSharp.TL\ObjectDeserializer.cs:line 20
   --- End of inner exception stack trace ---
   at TeleSharp.TL.ObjectUtils.DeserializeObject(BinaryReader reader) in TLSharp-master\TeleSharp.TL\ObjectDeserializer.cs:line 25
   at TeleSharp.TL.Messages.TLRequestGetHistory.DeserializeResponse(BinaryReader br) in TLSharp-master\TeleSharp.TL\TL\Messages\TLRequestGetHistory.cs:line 62
   at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request) in TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 344
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request) in TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 206
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext() in TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<RequestWithDcMigration>d__11.MoveNext() in TLSharp-master\TLSharp.Core\TelegramClient.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TLSharp.Core.TelegramClient.<SendRequestAsync>d__19`1.MoveNext() in TLSharp-master\TLSharp.Core\TelegramClient.cs:line 223
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at HaniYar.TLSharpMethods.<SendForwardMessageLast>d__73.MoveNext()

**Comment by hanigamini** [comment]
Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. : System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.Network.TcpTransport.<Receieve>d__4.MoveNext() in TLSharp-master\TLSharp.Core\Network\TcpTransport.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext() in TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<RequestWithDcMigration>d__11.MoveNext() in TLSharp-master\TLSharp.Core\TelegramClient.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TLSharp.Core.TelegramClient.<SendRequestAsync>d__19`1.MoveNext() in TLSharp-master\TLSharp.Core\TelegramClient.cs:line 223
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at HaniYar.TLSharpMethods.<GetLastPostId>d__70.MoveNext()

**Comment by benjaminhpang** [comment]
hi @knocte I have similar exception. Could you help take a look? Appreciate it.

2018-10-10T16:28:18.266 [Error] Error occurred: System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 149.154.175.50:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
   at TLSharp.Core.Network.TcpTransport..ctor(String address, Int32 port, TcpClientConnectionHandler handler) in D:\BPDE\git\SignalProviderInterface\TLSharp.Core\Network\TcpTransport.cs:line 22
   at TLSharp.Core.TelegramClient..ctor(Int32 apiId, String apiHash, ILogger logger, ISessionStore store, String sessionUserId, TcpClientConnectionHandler handler) in D:\BPDE\git\SignalProviderInterface\TLSharp.Core\TelegramClient.cs:line 51
   at SignalProviderInterface.Scraper.FindNewMessages.<GetTelegramClient>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at SignalProviderInterface.Scraper.FindNewMessages.<ReadMessages>d__3.MoveNext() (Id=248768, InvocationId=df26b675-9749-4b65-a726-3089d527bffb)
2018-10-10T16:28:18.266 [Error] System.Net.Sockets.SocketException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 149.154.175.50:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot,SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address,Int32 port)
   at TLSharp.Core.Network.TcpTransport..ctor(String address,Int32 port,TcpClientConnectionHandler handler) at D:\BPDE\git\SignalProviderInterface\TLSharp.Core\Network\TcpTransport.cs : 22
   at TLSharp.Core.TelegramClient..ctor(Int32 apiId,String apiHash,ILogger logger,ISessionStore store,String sessionUserId,TcpClientConnectionHandler handler) at D:\BPDE\git\SignalProviderInterface\TLSharp.Core\TelegramClient.cs : 51

**Comment by benjaminhpang** [comment]
I found the issue to my problem (might not apply to you). I am using Azure function to run my program and sometimes they would save the state on file storage, and rerun later on.

This timeout error will happen when TelegramClient is deserialized and run again.
