### ISSUE TITLE
msg_seqno too low

### ISSUE THREAD

**Issue by hanigamini** [sochix/TLSharp#777]
Hello,
I have this error,please help me.

msg_seqno too low (the server has already received a message with a lower msg_id but with either a higher or an equal and odd seqno) : System.InvalidOperationException: msg_seqno too low (the server has already received a message with a lower msg_id but with either a higher or an equal and odd seqno)
   at TLSharp.Core.Network.MtProtoSender.HandleBadMsgNotification(UInt64 messageId, Int32 sequence, BinaryReader messageReader) in TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 389
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request) in TLSharp.Core\Network\MtProtoSender.cs:line 200
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__9.MoveNext() in TLSharp.Core\Network\MtProtoSender.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at TLSharp.Core.TelegramClient.<ConnectAsync>d__9.MoveNext() in TLSharp.Core\TelegramClient.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at HaniYar.TLSharpMethods.<ReConnectClient>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at HaniYar.TLSharpMethods.<SendForwardMessageLast>d__74.MoveNext().

**Comment by hanigamini** [comment]
@knocte 
Hi,
Most when working parallel or changing the IP or system clock,please help me.

**Comment by hosseinGanjyar** [comment]
I've had same problem. I call a request 4 times and get this error, but after 5th reques I get success.
Please help if you know anything.
Thanks

**Comment by lobuz1** [comment]
Hi guys,
Same problem here. Did you managed to solve it?

**Comment by n3nikita** [comment]
Same problem here. Check #668 to get some details.
