### ISSUE TITLE
the TLContacts don't have the users definition.

### ISSUE THREAD

**Issue by kensonlai28** [sochix/TLSharp#814]
//get available contacts
            var result = await client.GetContactsAsync();

//find recipient in contacts
            var user = result.users.lists
                .Where(x => x.GetType() == typeof(TLUser))
                .Cast<TLUser>()
                .Where(x => x.first_name == "ZRX");

The  result.users.lists shows an error, how could I fix it?

**Comment by knocte** [comment]
What errors? Copy+paste the whole `ex.ToString()` here.

**Comment by kensonlai28** [comment]
Hello, 
 
  Thank you for your help. My question is about using TLSharp. I just use the very simple form to get Telegram users' phone information.
 
  The object returns from the client.GetContactsAsync() assigned for result variable, but it shows the error as follow. Could you please let me know how to handle it?
 
  I am using Visual studio 2017 & C# Programming language for this application. 
 
Error	CS1061	'TLContacts' does not contain a definition for 'users' and no extension method 'users' accepting a first argument of type 'TLContacts' could be found (are you missing a using directive or an assembly reference?)

**Comment by knocte** [comment]
That's a compiler error, not a runtime error, which means you're not using the API properly. Are you following a sample in the documentation? Is the sample wrong?

**Comment by kensonlai28** [comment]
Yes, I follow the sample in the documentation. Which API I should use? There maybe something wrong in the sample or some steps I have missed. 
 
Could you let me know how to run the sample correctly?
 
Thanks you,

**Comment by kensonlai28** [comment]
Could you tell me what library should I use?

**Comment by kensonlai28** [comment]
var code = "<code_from_telegram>";

What code should I put for the <code_from_telegram>?

**Comment by kensonlai28** [comment]
When I run the following code:
string hash = await client.SendCodeRequestAsync("+userphone");

I get the following error:
System.Net.Sockets.SocketException
  HResult=0x80004005
  Message=使用了与请求的协议不兼容的地址。 [2001:b28:f23f:f005::a]:443
  Source=System
  StackTrace:
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
   at TLSharp.Core.Network.TcpTransport..ctor(String address, Int32 port, TcpClientConnectionHandler handler)
   at TLSharp.Core.TelegramClient.<ReconnectToDcAsync>d__10.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TLSharp.Core.TelegramClient.<RequestWithDcMigration>d__11.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TLSharp.Core.TelegramClient.<SendCodeRequestAsync>d__14.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WindowsFormsApp1.telegramPhone.<button1_Click>d__2.MoveNext() in C:\Users\Administrator\Documents\Visual Studio 2017\Backup Files\WindowsFormsApp1\WindowsFormsApp1\telegramPhone.cs:line 32

How should I fix this?
