### ISSUE TITLE
Auth-key-unregistered

### ISSUE THREAD

**Issue by DelaNed** [sochix/TLSharp#87]
I received “Auth-key-unregistered” error.
I have copied api_hash and api_id in telegramClient.cs and changed the code with the one I received from telegram. All the phone numbers in app.config are in international format without “+” or “00”.
I called ImportContactByPhoneNumber() in my code snippet but in ‘HandleRpcResult’ (which is in MtProtoSender) it keeps giving the error “Auth_key_unregistered”.

**Comment by sochix** [comment]
Can you please copy and paste your code snippet, and stacktrace.

**Comment by DelaNed** [comment]
it's my code snippet i just dropped a button:
private async void button1_Click(object sender, EventArgs e)
        {
            Init(); //to initiate the 3 value from app.config
            await ImportContactByPhoneNumberAndSendMessage();
        }

**Comment by sochix** [comment]
I need your Init() code and ImportContactByPhoneNumberAndSendMessage() as well, and a stacktrace

**Comment by DelaNed** [comment]
Dear sochix
I really Appreciate your help.
The init() and ImportContactByPhoneNumberAndSendMessage() are functions that are written in your library (the latest Version), I just copied them but anyway, I attached a file that all the functions I used are written.
The stacktrace is :
   at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, MTProtoRequest request) in E:\Delaram nedaei\Downloads\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 288
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, MTProtoRequest request) in E:\Delaram nedaei\Downloads\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 193
   at TLSharp.Core.Network.MtProtoSender.<Recieve>d__9.MoveNext() in E:\Delaram nedaei\Downloads\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<ImportContactByPhoneNumber>d__16.MoveNext() in E:\Delaram nedaei\Downloads\TLSharp-master\TLSharp.Core\TelegramClient.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyApp.MyApp.<ImportContactByPhoneNumberAndSendMessage>d__17.MoveNext() in E:\Delaram nedaei\Downloads\TLSharp-master\MyApp\MyApp.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MyApp.MyApp.<button1_Click>d__21.MoveNext() in E:\Delaram nedaei\Downloads\TLSharp-master\MyApp\MyApp.cs:line 114

MyApp.cs.docx is attached


[MyApp.cs.docx](https://github.com/sochix/TLSharp/files/121310/MyApp.cs.docx)

**Comment by sochix** [comment]
You call 
```
var store = new FileSessionStore();
            var client = new TelegramClient(store, "session");

            await client.Connect();
```

in every method.

You need firstly create connection and client. Than use it in other methods.

**Comment by DelaNed** [comment]
@sochix  I changed the code and call 
`var store = new FileSessionStore();`
`var client = new TelegramClient(store, "session");`
`await client.Connect();`
only once but still get the same error.
I Changed my code to:
`

namespace MyApp
{
    public partial class MyApp : Form
    {
        private string numberToSendMessage { get; set; }

        private string NumberToAuthenticate { get; set; }

        private string UserNameToSendMessage { get; set; }
        public void Init()
        {
            // Setup your phone numbers in app.config
            NumberToAuthenticate = ConfigurationManager.AppSettings["numberToAuthenticate"];
            if (string.IsNullOrEmpty(NumberToAuthenticate))
                throw new InvalidOperationException("NumberToAuthenticate is null. Specify number in app.config");

            numberToSendMessage = ConfigurationManager.AppSettings["numberToSendMessage"];
            if (string.IsNullOrEmpty(numberToSendMessage))
                throw new InvalidOperationException("NumberToSendMessage is null. Specify number in app.config");

            UserNameToSendMessage = ConfigurationManager.AppSettings["userNameToSendMessage"];
            if (string.IsNullOrEmpty(UserNameToSendMessage))
                throw new InvalidOperationException("UserNameToSendMessage is null. Specify userName in app.config");

        }

        public MyApp()
        {
            InitializeComponent();
        }

        private async void button1_Click(object sender, EventArgs e)
        {
            Init();
            var store = new FileSessionStore();
            var client = new TelegramClient(store, "session");
            await client.Connect();

            var res = await client.ImportContactByPhoneNumber("989123890166");

            await client.SendMessage(res.Value, "Test message from TelegramClient");
        }
    }
}`

and this is the stack trace:

   at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, MTProtoRequest request) in E:\Downloads\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 288
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, MTProtoRequest request) in E:\Downloads\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 193
   at TLSharp.Core.Network.MtProtoSender.<Recieve>d__9.MoveNext() in E:\Downloads\TLSharp-master\TLSharp.Core\Network\MtProtoSender.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<ImportContactByPhoneNumber>d__16.MoveNext() in E:\Downloads\TLSharp-master\TLSharp.Core\TelegramClient.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyApp.MyApp.<button1_Click>d__14.MoveNext() in E:\Downloads\TLSharp-master\MyApp\MyApp.cs:line 53

**Comment by sochix** [comment]
To send messages you need to be authorized. Check existence of session.dat file and client.IsUserAuthorized(). Read manual carefully, please. https://github.com/sochix/TLSharp#using-tlsharp

**Comment by MaryamMlk** [comment]
I have the same problem: "AUTH_KEY_UNREGISTERED".
this is my code in mvc ,2 actions :
1)first action(Get) is for connecting to server:
     var store = new FileSessionStore();
     client = new TelegramClient(store, sessionUserId: "session");
      await client.Connect();
      var hash = await client.SendCodeRequest("myPhoneNumber");
   
2)then action(Post) is for authenticationg:
var user = await client.MakeAuth("myPhoneNumber", Session["hash"].ToString(), code);
.....................................................................
after connection and authentication , I called other actions for:
    var ImportContactByPhoneNumber = await client.ImportContactByPhoneNumber(phone);
......................................................................
I checked the existence of session.dat in "C:\\Program Files (x86)\\IIS Express\\session.dat"
and 
the client.IsUserAuthorized() is True

**Comment by ayazzali** [comment]
me too
I have exactly the same problem

**Comment by mmehdidehghani** [comment]
Hi everybody
I don't understand how can i authorize user! :( 
I don't understand how can i use "code" in this method:  client.MakeAuth
the code send to telegram and how can i use it in my project. and it become generate every time that i call "SendCodeRequest" method.
Please help me. I have searched it for hours and i can't fix it :((((

**Comment by ayazzali** [comment]
hi go to the tutorial? Show your code.

**Comment by mmehdidehghani** [comment]
Hi ayazzali
Thanks for you reply.
I attached my code. I change the .zip prefix to .docx cause of attachment limitation.
Would you please check it and help me? 

[TelCode.docx](https://github.com/sochix/TLSharp/files/827278/TelCode.docx)

Thanks

**Comment by mmehdidehghani** [comment]
Hi ayazzali
I solved that problem.
I have an another question.
I want to return all messages of the specified channel.
when i use "GetHistoryAsync" method, It returns only 100 message!!
Could you please help me?

Best Regards
Thanks

**Comment by ayazzali** [comment]
Hello, i'm sorry. i don't now .
but in this issue similar https://github.com/sochix/TLSharp/issues/383

**Comment by mmehdidehghani** [comment]
Hi ayazzali
Thank you so muchhhhhhh. 
It solved.  :)

Best Regards.

**Comment by lokialice** [comment]
client.IsUserAuthorized() == true but it also get error Auth-key-unregistered please help me
