### ISSUE TITLE
Error 10051 downloading photo

### ISSUE THREAD

**Issue by Xmg92** [sochix/TLSharp#877]
Hi everyone!

I'm new to this client library and pretty much to programming. I'm trying to download a photo from a Telegram channel with the following Task:

`        public async Task<string> ReadMessageImage(TLPhoto photo)
        {
            try
            {
                TLPhotoSize photoSize = photo.Sizes.ToList().OfType<TLPhotoSize>().Last();
                TLFileLocation tf = (TLFileLocation)photoSize.Location;        

                TLAbsInputFileLocation TLAbsInputFileLocation = new TLInputFileLocation()
                {               
                    LocalId = tf.LocalId,
                    Secret = tf.Secret,
                    VolumeId = tf.VolumeId
                };
                TLInputFileLocation TLInputFileLocation = TLAbsInputFileLocation as TLInputFileLocation;

                TeleSharp.TL.Upload.TLFile buffer = await client.GetFile(TLInputFileLocation, 1024 * 512);

               //Some more code in here

            }
            catch (Exception ex)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine($"There was an exception: {ex.ToString()}");
                Console.ResetColor();
                return null;
            }
        }`

The problem is when i get to the client.GetFile part i get the following error:

`ex.Message  
  A socket operation was attempted to an unreachable network [2001:b28:f23f:f005::a]:443	
ex.ErrorCode
   10051
ex.Source
   System
ex.StackTrace
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at TLSharp.Core.Network.TcpTransport..ctor(String address, Int32 port, TcpClientConnectionHandler handler)
   at TLSharp.Core.TelegramClient.<ReconnectToDcAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TLSharp.Core.TelegramClient.<RequestWithDcMigration>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TLSharp.Core.TelegramClient.<SendRequestAsync>d__18`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<GetFile>d__25.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Telegram.Telegram.<ReadMessageImage>d__23.MoveNext() in D:\Visual Studio\Trading - Copy\Telegram\Telegram.cs:line 164`

What i am doing wrong? Any help will be much aprreciated!

**Comment by Gawiga** [comment]
Hi @Xmg92, have you done your configuration at [my.telegram.org](http://my.telegram.org)?
After that you have to instantiate the client class with your configuration, as showed at the README file.
[I believe that is not a library error](https://stackoverflow.com/questions/5164466/a-socket-operation-was-attempted-to-an-unreachable-host)

**Comment by Xmg92** [comment]
Hi @Gawiga, i have been doing some more research with the information you provided and i still really don't know where the problem is.

I've tried using the exact same code in other channels and and i can download a photo as expected. But there is one particular channel i'm substribed that gives me the error shown before. 

Can it be something related with the channel configuration? Is it possible to configure a channel to avoid photo downloads?
