### ISSUE TITLE
i-get-a-xxxmigrationexception-or-a-migrate_x-error

### ISSUE THREAD

**Issue by deepak22123r** [sochix/TLSharp#879]
During running application got below exception

"Phone number registered to a different DC: 5. See: https://github.com/sochix/TLSharp#i-get-a-xxxmigrationexception-or-a-migrate_x-error"

please help

**Comment by knocte** [comment]
Please post full exception, not just the exception message.

So, this string: `ex.ToString()`

**Comment by thaarsoft** [comment]
i am also facing same issue. here is the stack 


System.Exception: Telegram server replied requesting a migration to DataCenter 5 when this connection was already using this DataCenter ---> TLSharp.Core.Network.Exceptions.PhoneMigrationException: Phone number registered to a different DC: 5. See: https://github.com/sochix/TLSharp#i-get-a-xxxmigrationexception-or-a-migrate_x-error
   at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<RequestWithDcMigration>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at TLSharp.Core.TelegramClient.<RequestWithDcMigration>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TLSharp.Core.TelegramClient.<SendCodeRequestAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WindowsFormsApp1.Form1.<GetUsers>d__9.MoveNext() in C:\Freelancer\Products\Telegram\WindowsFormsApp1\WindowsFormsApp1\Form1.cs:line 149
