### ISSUE TITLE
I get a xxxMigrationException or a MIGRATE_X error!

### ISSUE THREAD

**Issue by thaarsoft** [sochix/TLSharp#902]
I got exception for migration. i am attaching the stack track

System.Exception: Telegram server replied requesting a migration to DataCenter 5 when this connection was already using this DataCenter ---> TLSharp.Core.Network.Exceptions.PhoneMigrationException: Phone number registered to a different DC: 5. See: https://github.com/sochix/TLSharp#i-get-a-xxxmigrationexception-or-a-migrate_x-error
   at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, TLMethod request)
   at TLSharp.Core.Network.MtProtoSender.<Receive>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Core.TelegramClient.<RequestWithDcMigration>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at TLSharp.Core.TelegramClient.<RequestWithDcMigration>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TLSharp.Core.TelegramClient.<SendCodeRequestAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WindowsFormsApp1.Form1.<GetUsers>d__9.MoveNext() in C:\Freelancer\Products\Telegram\WindowsFormsApp1\WindowsFormsApp1\Form1.cs:line 149

**Comment by thaarsoft** [comment]
I have pull down the latest  master class and use after deleting .dat file in bin folder.

**Comment by thaarsoft** [comment]
[CodeSnippt.txt](https://github.com/sochix/TLSharp/files/4113319/CodeSnippt.txt)

i have uploded the code and i am getting error at line#29.

**Comment by knocte** [comment]
@thaarsoft sorry for the last reply, I'm really surprised this could happen, I wish I could reproduce this problem so I could fix it myself 🤔

**Comment by knocte** [comment]
s/last/late
