### ISSUE TITLE
File session corrupted

### ISSUE THREAD

**Issue by solarin** [sochix/TLSharp#932]
Hello,
It happened that after closing the application, restarting the application, the software wasn't able to connect throwing an exception that i don't have right now and I had to delete the session file and reauthenticate again.

I didn't see properly how this file is working, so, what can go wrong in this file to make this happen?

is the session storing information regarding the expected bytes to receive from the server?

**Comment by knocte** [comment]
If you didn't save a copy of the file, we can only speculate.

**Comment by solarin** [comment]
the telephone i used was marked as spammer because it tried to reconnect too fast, shit! i need to wait 3 hours.

**Comment by knocte** [comment]
> the telephone i used was marked as spammer because it tried to reconnect too fast, shit! i need to wait 3 hours.

That sounds like a different problem, not related to this issue.

**Comment by solarin** [comment]
this is what you get if the session file is "dirty" and you try to connect

> System.InvalidOperationException: Can't decode packet
>    at TLSharp.Core.Network.MtProtoSender.DecodeMessage(Byte[] body) in source\repos\TLSharp\TLSharp.Core\Network\MtProtoSender.cs:line 115
>    at TLSharp.Core.Network.MtProtoSender.<Receive>d__8.MoveNext() in source\repos\TLSharp\TLSharp.Core\Network\MtProtoSender.cs:line 141
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at TLSharp.Core.TelegramClient.<ConnectAsync>d__13.MoveNext() in source\repos\TLSharp\TLSharp.Core\TelegramClient.cs:line 107
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at test_console.Program.<dothings>d__2.MoveNext() in source\repos\test-console\test-console\Program.cs:line 29
>

**Comment by solarin** [comment]
this makes me think that the session file is storing some information about the next expected packet

**Comment by knocte** [comment]
> the telephone i used was marked as spammer because it tried to reconnect too fast, shit! i need to wait 3 hours.

was that telephone emirati? Maybe related to issue 935?

**Comment by solarin** [comment]
> the telephone i used was marked as spammer because it tried to reconnect too fast, shit! i need to wait 3 hours.
> 
> was that telephone emirati? Maybe related to issue 935?

no no this is a vietnamese number, the one that was working

**Comment by solarin** [comment]
this session file problem exists regardless of the number. so let's keep separated from #935

**Comment by solarin** [comment]
anybody has an idea of which fields in the session object can cause the communication to abort?

if sequence is not updated for example?
